security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        user_from_db:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        unsec:
            pattern: ^/(login|login_check)
            anonymous: ~
            security: false

        admin_dashboard:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
                username_parameter: form[username]
                password_parameter: form[password]
            logout:
                path: /logout
#
#    access_conrol:
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
