security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    alex:
                        password: qwerty
                        roles: ROLE_ADMIN
                    test:
                        password: qwerty
                        roles: ROLE_USER
        user_from_db:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        unsec:
            pattern: ^/(login|registration)$
            anonymous: ~

        admin_dashboard:
            pattern: ^/
            form_login:
                provider: in_memory
                login_path: login
                check_path: login_check
                username_parameter: form[username]
                password_parameter: form[password]
            logout:
                path: logout

    access_control:
        - { path: ^/(login|registration), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
